FROM python:3.8.12-slim

WORKDIR /usr/src

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN pip install --upgrade pip
COPY ./project ./project
COPY requirements.web .

RUN pip install -r requirements.web

